[package]
name = "collector"
version = "0.1.0"
edition = "2021"


[dependencies]
walkdir = "2"
sha2 = "0.10"
goblin = "0.6"
anyhow = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hex = "0.4"
rayon = "1"
